# Generated by Django 4.0.1 on 2022-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='region1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=300)),
                ('country', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('reportname', models.CharField(max_length=300)),
                ('base_year', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('geography', models.CharField(max_length=300)),
                ('market', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=300)),
                ('year', models.JSONField()),
                ('ASP', models.JSONField(blank=True, null=True)),
                ('toc', models.JSONField()),
                ('tocprocessed', models.JSONField()),
                ('value', models.BooleanField()),
                ('volume', models.BooleanField()),
                ('creator', models.CharField(max_length=300)),
                ('valueunit', models.CharField(blank=True, max_length=300, null=True)),
                ('volumeunit', models.CharField(blank=True, max_length=300, null=True)),
                ('reportloc', models.CharField(blank=True, max_length=600, null=True)),
                ('regiondet', models.JSONField()),
                ('createddate', models.DateField(auto_now=True)),
                ('tablesplit', models.BooleanField(default=False)),
                ('region', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
