# Generated by Django 4.0.1 on 2022-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='region',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='tablesplit',
        ),
    ]
