# Generated by Django 4.0.1 on 2022-05-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0002_remove_reports_region_remove_reports_tablesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='region',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='tablesplit',
            field=models.BooleanField(default=False),
        ),
    ]
