# Generated by Django 4.0.1 on 2022-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0003_reports_region_reports_tablesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='excelreport',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='reportloc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
