# Generated by Django 4.0.1 on 2022-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0004_reports_excelreport_alter_reports_reportloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='reportFlag',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
