# Generated by Django 4.0.1 on 2022-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0005_reports_reportflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='regiondet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
